Method analysis
TestingResearchIllinois/starts pull request #106
Opened 2023-08-22 20:33 UTC by mmk-1

2023-08-23 08:42 UTC, mmk-1 commented
This PR adds the following things:
- Updates maven-plugin-plugin to 3.6.4 to enable us to use ASM 9.5. The ASM dependencies are also added to the pom file as well.
- a ZLC helper function that enables us to do method level analysis and save files.
- The added smethod folder includes the essential source files that builds the method-level dependency graph and finds checksums.
- The ChecksumUtil.java file has 2 new methods added to it which is required for method-level analysis.
- StartsConstants.java has some new constants added to it which is used in the other method-level related files.

All the other changed files are the new commits made in the impacted-both-ways but since the forked branch mixed-granularity is 3 commits behind, these changes aren't reflected. The changes from my inspection is just fixing transitive closure options to PS1, PS2 and PS3.

2023-08-25 04:08 UTC, owolabileg requested changes
I commented on one reeeeeeeeeeeeeeally long class. I do not understand much of what is being done here; so I am hoping that the comments that you will add can help me understand. I will look more later.

2023-08-25 04:08 UTC, owolabileg commented on .gitignore
> +.vscode/
add new line to the end of the file

2023-08-25 04:08 UTC, owolabileg commented on pom.xml
> +    <!-- https://mvnrepository.com/artifact/org.ow2.asm/asm -->
remove the comment

2023-08-25 04:08 UTC, owolabileg commented on starts-core/src/main/java/edu/illinois/starts/constants/StartsConstants.java
> +    String METHODS_TEST_DEPS_ZLC_FILE_TM = "method-deps-tm.zlc";
what is `tm` referring to here? can you please add a comment for that?

2023-08-25 04:08 UTC, owolabileg commented on starts-core/src/main/java/edu/illinois/starts/helpers/ZLCHelperMethods.java
> +    public static void writeZLCFile(Map<String, Set<String>> method2tests, Map<String, String> checksumsMap,
method2tests --> methodsToTests

2023-08-25 04:08 UTC, owolabileg commented on starts-core/src/main/java/edu/illinois/starts/helpers/ZLCHelperMethods.java
> +        long start = System.currentTimeMillis();
`long` does not seem aligned with `LOGGER` on the next line. Please check that they are.

2023-08-25 04:08 UTC, owolabileg commented on starts-core/src/main/java/edu/illinois/starts/helpers/ZLCHelperMethods.java
> +
add a comment describing this method

2023-08-25 04:08 UTC, owolabileg commented on starts-core/src/main/java/edu/illinois/starts/helpers/ZLCHelperMethods.java
> +
add a comment describing this method

2023-08-25 04:08 UTC, owolabileg commented on starts-core/src/main/java/edu/illinois/starts/helpers/ZLCHelperMethods.java
> +    public static void writeZLCFileH(Map<String, Set<String>> method2tests, Map<String, String> methodsChecksums,
expand the `H` in `writeZLCFileH`... what does it stand for?

2023-08-25 04:08 UTC, owolabileg commented on starts-core/src/main/java/edu/illinois/starts/helpers/ZLCHelperMethods.java
> +        LOGGER.log(Level.FINE, "ZLC format: " + format.toString());
align the start of the last two lines

2023-08-25 04:08 UTC, owolabileg commented on starts-core/src/main/java/edu/illinois/starts/helpers/ZLCHelperMethods.java
> +
add comments to explain what is produced by `createZLCFileData` and `createZLCFileDataClasses`

2023-08-25 04:08 UTC, owolabileg commented on starts-core/src/main/java/edu/illinois/starts/helpers/ZLCHelperMethods.java
> +
also, explain add comments to clarify why `zlc` is assigned twice

2023-08-25 04:08 UTC, owolabileg commented on starts-core/src/main/java/edu/illinois/starts/helpers/ZLCHelperMethods.java
> +
add a comment to describe what this method does.

2023-08-25 04:08 UTC, owolabileg commented on starts-core/src/main/java/edu/illinois/starts/helpers/ZLCHelperMethods.java
> +    public static void writeZLCFileTM(Map<String, Set<String>> method2tests, Map<String, String> checksumsMap,
what does `TM` mean in the name of the method? write in full

2023-08-25 04:08 UTC, owolabileg commented on starts-core/src/main/java/edu/illinois/starts/helpers/ZLCHelperMethods.java
> +    public static void writeZLCFileTM(Map<String, Set<String>> method2tests, Map<String, String> checksumsMap,
method2tests --> methodToTests

2023-08-25 04:08 UTC, owolabileg commented on starts-core/src/main/java/edu/illinois/starts/helpers/ZLCHelperMethods.java
> +
add a comment to describe what this method does.

2023-08-25 04:08 UTC, owolabileg commented on starts-core/src/main/java/edu/illinois/starts/helpers/ZLCHelperMethods.java
> +    public static void writeZLCFileHTM(Map<String, Set<String>> method2tests, Map<String, String> methodsChecksums,
What does HTM mean? Write in full.

also, method2tests --> methodToTests

2023-08-25 04:08 UTC, owolabileg commented on starts-core/src/main/java/edu/illinois/starts/helpers/ZLCHelperMethods.java
> +        LOGGER.log(Level.FINE, "ZLC format: " + format.toString());
ensure that the last two lines start from the same column

2023-08-25 04:08 UTC, owolabileg commented on starts-core/src/main/java/edu/illinois/starts/helpers/ZLCHelperMethods.java
> +
I have seen these lines multiple times line, and they seem identical to me. Why the code duplication/repetition?

2023-08-25 04:08 UTC, owolabileg commented on starts-core/src/main/java/edu/illinois/starts/helpers/ZLCHelperMethods.java
> +
add a comment to describe what this method does.

2023-08-25 04:08 UTC, owolabileg commented on starts-core/src/main/java/edu/illinois/starts/helpers/ZLCHelperMethods.java
> +
add a comment explaining what this method does

2023-08-25 04:08 UTC, owolabileg commented on starts-core/src/main/java/edu/illinois/starts/helpers/ZLCHelperMethods.java
> +    public static ZLCFileContent createZLCFileData(
there seems to be a lot of replication in the code of this method and the previous one. please refactor

2023-08-25 04:08 UTC, owolabileg commented on starts-core/src/main/java/edu/illinois/starts/helpers/ZLCHelperMethods.java
> +
add a comment describing this method

2023-08-25 04:08 UTC, owolabileg commented on starts-core/src/main/java/edu/illinois/starts/helpers/ZLCHelperMethods.java
> +            Map<String, Set<String>> method2methods,
method2tests --> methodToTests

2023-08-25 04:08 UTC, owolabileg commented on starts-core/src/main/java/edu/illinois/starts/helpers/ZLCHelperMethods.java
> +        ArrayList<String> methodList = new ArrayList<>(method2methods.keySet()); // all tests
method2methods --> methodToMethods

2023-08-25 04:08 UTC, owolabileg commented on starts-core/src/main/java/edu/illinois/starts/helpers/ZLCHelperMethods.java
> +            String methodName = methodPath.split("#")[1].replace("()", "");
these string operations are going to be costly

2023-08-25 04:08 UTC, owolabileg commented on starts-core/src/main/java/edu/illinois/starts/helpers/ZLCHelperMethods.java
> +                String method1 = appendParametersToMethodName(method);
method1 --> use a more descriptive variable name

2023-08-25 04:08 UTC, owolabileg commented on starts-core/src/main/java/edu/illinois/starts/helpers/ZLCHelperMethods.java
> +                // } else {
delete

2023-08-25 04:08 UTC, owolabileg commented on starts-core/src/main/java/edu/illinois/starts/helpers/ZLCHelperMethods.java
> +                // }
delete

2023-08-25 04:08 UTC, owolabileg commented on starts-core/src/main/java/edu/illinois/starts/helpers/ZLCHelperMethods.java
> +
I will stop writing these, but please make sure you add comments to describe all methods

2023-08-25 04:08 UTC, owolabileg commented on starts-core/src/main/java/edu/illinois/starts/helpers/ZLCHelperMethods.java
> +    public static List<Set<String>> getChangedDataH(ClassLoader loader, String artifactsDir, boolean cleanBytes,
I will also stop writing these, but please use full words, not letters in method names

2023-08-25 04:08 UTC, owolabileg commented on starts-core/src/main/java/edu/illinois/starts/helpers/ZLCHelperMethods.java
> +            // on PLAIN_TEXT, testsCount+1 will starts from 0
what is PLAIN_TEXT referring to in the program?

2023-08-25 04:08 UTC, owolabileg commented on starts-core/src/main/java/edu/illinois/starts/helpers/ZLCHelperMethods.java
> +            // on PLAIN_TEXT, testsCount+1 will starts from 0
starts --> start

2023-08-25 04:08 UTC, owolabileg commented on starts-core/src/main/java/edu/illinois/starts/helpers/ZLCHelperMethods.java
> +            // on PLAIN_TEXT, testsCount+1 will starts from 0
same comments as above

2023-08-25 04:08 UTC, owolabileg commented on starts-core/src/main/java/edu/illinois/starts/helpers/ZLCHelperMethods.java
> +        }
this code is  mostly duplicated from the earlier loop. refactor

2023-08-25 04:08 UTC, owolabileg commented on starts-core/src/main/java/edu/illinois/starts/helpers/ZLCHelperMethods.java
> +            // on PLAIN_TEXT, testsCount+1 will starts from 0
same comments as above

2023-08-25 04:08 UTC, owolabileg commented on starts-core/src/main/java/edu/illinois/starts/helpers/ZLCHelperMethods.java
> +        }
more similar code that should be refactored

2023-08-25 04:08 UTC, owolabileg commented on starts-core/src/main/java/edu/illinois/starts/helpers/ZLCHelperMethods.java
> +    }
This previous method is over a 100 lines long! It should be split and refactored to make is understandable!

2023-08-25 04:08 UTC, owolabileg commented on starts-core/src/main/java/edu/illinois/starts/helpers/ZLCHelperMethods.java
> +}
add new line at the end

2023-08-26 02:54 UTC, owolabileg requested changes

2023-08-26 02:54 UTC, owolabileg commented on starts-core/src/main/java/edu/illinois/starts/helpers/ZLCHelperMethods.java
> +        result.add(changedClasses);
replace with `Collections.addAll(result, changedMethods, newMethods, affectedTests, ...);`

2023-08-26 02:54 UTC, owolabileg commented on starts-core/src/main/java/edu/illinois/starts/smethods/ClassToMethodsCollectorCV.java
> +}
add new line at the end of the file

2023-08-26 02:54 UTC, owolabileg commented on starts-core/src/main/java/edu/illinois/starts/smethods/FileUtil.java
> +    public static void saveMap(Map<String, Set<String>> mapToStore, String dirName, String fileName) throws Exception {
I think we have a [util class for this](https://github.com/TestingResearchIllinois/starts/blob/master/starts-core/src/main/java/edu/illinois/starts/helpers/Writer.java) in STARTS

2023-08-26 02:54 UTC, owolabileg commented on starts-core/src/main/java/edu/illinois/starts/smethods/FileUtil.java
> +    }
use try-with-resources so that you do not have to flush and close your own writer

2023-08-26 02:54 UTC, owolabileg commented on starts-core/src/main/java/edu/illinois/starts/smethods/Macros.java
> +}
new line at the end

2023-08-26 02:54 UTC, owolabileg commented on starts-core/src/main/java/edu/illinois/starts/smethods/Macros.java
> +public class Macros {
why not put all of these constants in StartsConstants.java? Is there a justification for a separate constants class?

2023-08-26 02:54 UTC, owolabileg commented on starts-core/src/main/java/edu/illinois/starts/smethods/MethodCallCollectorCV.java
> +}
new line at the end.

2023-08-26 02:54 UTC, owolabileg commented on starts-core/src/main/java/edu/illinois/starts/util/ChecksumUtil.java
> +                        // joda-convert-8.jar
this comment's wrapping does not look nice. Can you format better, while staying in the line width limit

2023-08-26 02:54 UTC, owolabileg commented on starts-core/src/main/java/edu/illinois/starts/smethods/MethodLevelStaticDepsBuilder.java
> +public class MethodLevelStaticDepsBuilder {
add a comment to describe what the class does

2023-08-26 02:54 UTC, owolabileg commented on starts-core/src/main/java/edu/illinois/starts/smethods/MethodLevelStaticDepsBuilder.java
> +    // -Dexec.args="path to test project"
do we really need these comments here?

2023-08-26 02:54 UTC, owolabileg commented on starts-core/src/main/java/edu/illinois/starts/smethods/MethodLevelStaticDepsBuilder.java
> +    public static Map<String, Set<String>> methodName2MethodNames = new HashMap<>();
methodName2MethodNames --> methodNameToMethodNames

2023-08-26 02:54 UTC, owolabileg commented on starts-core/src/main/java/edu/illinois/starts/smethods/MethodLevelStaticDepsBuilder.java
> +    public static Map<String, Set<String>> class2ContainedMethodNames = new HashMap<>();
class2ContainedMethodNames --> classToContainedMethodNames

2023-08-26 02:54 UTC, owolabileg commented on starts-core/src/main/java/edu/illinois/starts/smethods/MethodLevelStaticDepsBuilder.java
> +    // for every method, get the methods it invokes
is it `directly invokes` or `transitively invokes`?

2023-08-26 02:54 UTC, owolabileg commented on starts-core/src/main/java/edu/illinois/starts/smethods/MethodLevelStaticDepsBuilder.java
> +    public static Map<String, Set<String>> testClasses2methods = new HashMap<>();
testClasses2methods --> testClassesToMethods

Also, this field has no comment... add comment to be consistent

2023-08-26 02:54 UTC, owolabileg commented on starts-core/src/main/java/edu/illinois/starts/smethods/MethodLevelStaticDepsBuilder.java
> +    public static Map<String, Set<String>> method2testClasses = new HashMap<>();
method2testClasses --> methodToTestClasses

Also, this field has no comment... add comment to be consistent

2023-08-26 02:54 UTC, owolabileg commented on starts-core/src/main/java/edu/illinois/starts/smethods/MethodLevelStaticDepsBuilder.java
> +    public static Map<String, Set<String>> methods2testmethods = new HashMap<>();
methods2testmethods --> methodsToTestMethods

Also, this field has no comment... add comment to be consistent

2023-08-26 02:54 UTC, owolabileg commented on starts-core/src/main/java/edu/illinois/starts/smethods/MethodLevelStaticDepsBuilder.java
> +    public static Map<String, String> classesChecksums = new HashMap<>();
this field has no comment... add comment to be consistent

2023-08-26 02:54 UTC, owolabileg commented on starts-core/src/main/java/edu/illinois/starts/smethods/MethodLevelStaticDepsBuilder.java
> +    private static Map<String, String> methodsCheckSum = new HashMap<>();
this field has no comment... add comment to be consistent

2023-08-26 02:54 UTC, owolabileg commented on starts-core/src/main/java/edu/illinois/starts/smethods/MethodLevelStaticDepsBuilder.java
> +            if (className.contains("Test")) {
Would it be more precise to say classnames that start or end with `Test`? Also, are we also checking that the class is in `src/test`?

2023-08-26 02:54 UTC, owolabileg commented on starts-core/src/main/java/edu/illinois/starts/smethods/MethodLevelStaticDepsBuilder.java
> +
Add comment to describe this method

2023-08-26 02:54 UTC, owolabileg commented on starts-core/src/main/java/edu/illinois/starts/smethods/MethodLevelStaticDepsBuilder.java
> +
Add comment to describe this method

2023-08-26 02:54 UTC, owolabileg commented on starts-core/src/main/java/edu/illinois/starts/smethods/MethodLevelStaticDepsBuilder.java
> +
Add comment to describe this method

2023-08-26 02:54 UTC, owolabileg commented on starts-core/src/main/java/edu/illinois/starts/smethods/MethodLevelStaticDepsBuilder.java
> +    public static Map<String, Set<String>> computeMethod2testClasses() {
computeMethod2testClasses --> computeMethodToTestClasses

2023-08-26 02:54 UTC, owolabileg commented on starts-core/src/main/java/edu/illinois/starts/smethods/MethodLevelStaticDepsBuilder.java
> +            // String klas = ChecksumUtil.toClassName(methodPath.split("#")[0]);
remove

2023-08-26 02:54 UTC, owolabileg commented on starts-core/src/main/java/edu/illinois/starts/smethods/MethodLevelStaticDepsBuilder.java
> +
Add comment to describe this method

2023-08-26 02:54 UTC, owolabileg commented on starts-core/src/main/java/edu/illinois/starts/smethods/MethodLevelStaticDepsBuilder.java
> +
Add comment to describe this method

2023-08-26 02:54 UTC, owolabileg commented on starts-core/src/main/java/edu/illinois/starts/smethods/MethodLevelStaticDepsBuilder.java
> +
Add comment to describe this method

2023-08-26 02:54 UTC, owolabileg commented on starts-core/src/main/java/edu/illinois/starts/smethods/MethodLevelStaticDepsBuilder.java
> +
Add comment to describe this method

2023-08-26 02:54 UTC, owolabileg commented on starts-core/src/main/java/edu/illinois/starts/smethods/MethodLevelStaticDepsBuilder.java
> +
Add comment to describe this method

2023-08-26 02:54 UTC, owolabileg commented on starts-core/src/main/java/edu/illinois/starts/smethods/MethodLevelStaticDepsBuilder.java
> +    public static void computeMethod2TestMethods() {
computeMethod2TestMethods --> computeMethodToTestMethods

2023-08-26 02:54 UTC, owolabileg commented on starts-core/src/main/java/edu/illinois/starts/smethods/MethodLevelStaticDepsBuilder.java
> +
Add comment to describe this method

2023-08-26 02:54 UTC, owolabileg commented on starts-core/src/main/java/edu/illinois/starts/smethods/MethodLevelStaticDepsBuilder.java
> +    public static Set<String> getDepsHelper(String testClass) {
Add comment to describe this method

2023-08-26 02:54 UTC, owolabileg commented on starts-core/src/main/java/edu/illinois/starts/smethods/MethodLevelStaticDepsBuilder.java
> +
Add comment to describe this method

2023-08-26 02:54 UTC, owolabileg commented on starts-core/src/main/java/edu/illinois/starts/smethods/MethodLevelStaticDepsBuilder.java
> +                    // numMethodDepNodes.addAll(invokedMethods);
delete

2023-08-26 02:54 UTC, owolabileg commented on starts-core/src/main/java/edu/illinois/starts/smethods/MethodLevelStaticDepsBuilder.java
> +
Add comment to describe this method

2023-08-26 02:54 UTC, owolabileg commented on starts-core/src/main/java/edu/illinois/starts/smethods/MethodLevelStaticDepsBuilder.java
> +
Add comment to describe this method

2023-08-26 02:54 UTC, owolabileg commented on starts-core/src/main/java/edu/illinois/starts/smethods/MethodLevelStaticDepsBuilder.java
> +
Add comment to describe this method

2023-08-26 02:54 UTC, owolabileg commented on starts-core/src/main/java/edu/illinois/starts/smethods/MethodLevelStaticDepsBuilder.java
> +}
new line at the end

2023-08-26 02:55 UTC, owolabileg commented
I finished a pass over this huge PR, and make more (mostly cosmetic) change requests to help better understand what is being done.

2023-09-11 14:27 UTC, pengyuejiang commented on starts-core/src/main/java/edu/illinois/starts/helpers/Loadables.java
These closureOptions were already changed to PS1,2,3 in `impacted-both-ways` branch, right?`

2023-09-11 16:47 UTC, mmk-1 commented on starts-core/src/main/java/edu/illinois/starts/helpers/Loadables.java
Yes but mmk-1:method-analysis was branched from starts:mixed-granularity which didn't include the change. However I did merge it in this fork so that's why it is in the commits in the beginning

2023-09-11 18:11 UTC, pengyuejiang commented on starts-core/src/main/java/edu/illinois/starts/helpers/ZLCHelperMethods.java
> +     */
What do the other parameters do? For instance, what does `unreached` do? I didn't see it in the method body, should it be here at all? If the documentation for some of these parameters appear in another method, please refer me to it. Maybe write something like: `@param foo See parameter <code>foo</code> in method <code>bar</code>`

2023-09-11 18:37 UTC, pengyuejiang commented on starts-core/src/main/java/edu/illinois/starts/helpers/ZLCHelperMethods.java
> +            String space = WHITE_SPACE;
Why not just use the constant?

2023-09-11 18:39 UTC, pengyuejiang commented on starts-core/src/main/java/edu/illinois/starts/helpers/ZLCHelperMethods.java
> +            String space = WHITE_SPACE;
Same comment as above.

2023-09-11 18:41 UTC, pengyuejiang commented on starts-core/src/main/java/edu/illinois/starts/helpers/ZLCHelperMethods.java
> +        // Updating methods checksums for non changed classes
This way of calling it "non changed classes" can be a little bit confusing, I suggest something like "non changed but impacted classes"

2023-09-11 19:13 UTC, pengyuejiang commented on starts-core/src/main/java/edu/illinois/starts/smethods/ClassToMethodsCollectorCV.java
> +    Map<String, Set<String>> class2ContainedMethodNames;
Please write out `to` instead of `2`. (in this case `To` if it's not the first word of the variable name)

2023-09-11 19:14 UTC, pengyuejiang commented on starts-core/src/main/java/edu/illinois/starts/smethods/ClassToMethodsCollectorCV.java
> +    Map<String, Set<String>> hierarchyChildren;
What are these? Can you add a JavaDoc? Thanks!

2023-09-11 19:15 UTC, pengyuejiang commented on starts-core/src/main/java/edu/illinois/starts/smethods/MethodCallCollectorCV.java
> +    }
Make sure to add documentation comments for `public` methods.

2023-09-11 19:19 UTC, pengyuejiang commented on starts-core/src/main/java/edu/illinois/starts/smethods/ClassToMethodsCollectorCV.java
> +    @Override
What does this method do exactly? There must be a purpose for you to override this method, and it would be helpful if you write a JavaDoc about the specific function of this overrode `visit`. Same with other methods you implemented in addition to the base class (parent class).

2023-09-11 19:24 UTC, pengyuejiang commented on starts-core/src/main/java/edu/illinois/starts/util/ChecksumUtil.java
> +
They look almost identical, can you make them into one method that takes an argument (for instance `String extension`)?

2023-09-11 19:30 UTC, pengyuejiang requested changes
I've made some additional comments, please remember to address Owolabi's comments as well. If you are done addressing certain comments, make sure you mark that conversation as "Resolved."

2023-09-25 19:12 UTC, mmk-1 commented
I've addressed almost all comments. The only thing is refactoring the long getChangedDataHybrid() method in ZLCHelperMethods which I haven't been able to do yet without breaking the working logic in tests.

2023-09-30 11:56 UTC, mmk-1 commented
I have made change in the overall logic of saving the mappings. Now we use serialization. This way file manipualtion is way more efficient and makes the code in `ZLCHelperMethods` more readable.

2023-09-30 11:57 UTC, mmk-1 commented
> I have made change in the overall logic of saving the mappings. Now we use serialization. This way file manipualtion is way more efficient and makes the code in `ZLCHelperMethods` more readable.

Also variables are not in our dependencies by default. But we can have them by a flag when running starts.

2023-10-14 14:08 UTC, owolabileg approved these changes

2023-10-14 14:10 UTC, merged