Optimize method and hybrid starts by removing unecessary affected test classes computation
TestingResearchIllinois/starts pull request #110
Opened 2023-10-28 11:38 UTC by mmk-1

- I've removed the parts that computed `affectedTestClasses` for optimization.
- `nonAffectedMethods` variable was not used anyways in the code so I removed that too
- As an outcome of removing `affectedTestClasses` computations, `methodToTestClasses` mapping wasn't needed in `HybridMojo.java` either.

2023-10-28 16:43 UTC, owolabileg requested changes

2023-10-28 16:43 UTC, owolabileg commented on starts-plugin/src/main/java/edu/illinois/starts/jdeps/HybridMojo.java
> -            methodToTestClasses = MethodLevelStaticDepsBuilder.computeMethodToTestClasses();
I don't understand this change: what was it doing before?

2023-10-28 16:47 UTC, owolabileg commented
@mmk-1 let's think carefully about these changes, before merging them.

> I've removed the parts that computed affectedTestClasses for optimization.

IIUC, these affectedTestClasses maps method-level changes to the class level. Is that right? If so, we'd need something like that for experiments. So, instead of deleting, why not make it an option that the user can enable or disable?

> nonAffectedMethods variable was not used anyways in the code so I removed that too

It seems that you would need this variable when you later implement all the variants (e.g., to avoid instrumenting nonAffected methods. Does that make sense?

> As an outcome of removing affectedTestClasses computations, methodToTestClasses mapping wasn't needed in HybridMojo.java either.

Please see my comment above: should we make it an option instead of outright deleting it?

2023-10-29 07:30 UTC, mmk-1 commented on starts-plugin/src/main/java/edu/illinois/starts/jdeps/HybridMojo.java
> -            methodToTestClasses = MethodLevelStaticDepsBuilder.computeMethodToTestClasses();
This mapped methods to their dependent test classes. It was used before for finding affectedTestClasses

2023-10-29 07:32 UTC, mmk-1 commented
Yes you're right. I'll make changes to introduce a parameter to turn this feature on/off

2023-10-31 08:52 UTC, mmk-1 commented
@owolabileg I have added new parameters based on your reviews to make Affected Test Class computation optional. Please review. Thanks!

2023-11-02 00:23 UTC, owolabileg approved these changes

2023-11-02 00:24 UTC, owolabileg commented
This all looks good to me, and I think you can merge.

2023-11-07 13:35 UTC, merged