Add option for incremental dependency finding
TestingResearchIllinois/starts pull request #28
Opened 2017-11-15 06:08 UTC by hksskh

Add option for incremental dependency finding in STARTS:
1) in prepareForNextRun function in BaseMojo, pass changedClasses and newClasses to Loadables so that jdeps only find dependencies for changed and new classes instead of all classes in localpath
2) only find transitiveClosures for affected tests instead of all tests
3) update ZLC file with dependencies for changed classes, and add dependencies for new classes, instead of creating new ZLC file each time
You can use 'mvn starts:starts -DincrementalUpdate=true' to enable incremental dependency finding. 'computeUnreached' is also made an option in DiffMojo.

2017-11-16 14:45 UTC, owolabileg commented
@august782, @denizarsan, @milicahtanovic please help review this. It's a big PR, but @hksskh has agreed to make smaller, easier to review PRs in the future.

2017-11-21 03:21 UTC, hksskh commented
Nov. 20. 
Add two commits:
merge from STARTS master to integrate retestAll when jar changes
Add incrementalUpdate option to use in ImpactedMojo, and set up a standalone zlc file for ImpactedMojo

2017-11-21 03:59 UTC, owolabileg commented
@hksskh It's best if you don't add any more commits to this PR. Notice that no one else got the chance to review this yet, likely because it involves a lot of code changes at once. Thanks

2017-11-24 22:01 UTC, august782 commented on starts-core/src/main/java/edu/illinois/starts/helpers/Cache.java
> +        newJarClasses = new HashSet<>();// only place to clear new jar classes. carefully call this
It is kind of unclear that one needs to make a new Cache in order to clear the contents of a static variable. It would be better to make it a bit more transparent, perhaps with an explicit method.

On that note, it is also unclear why newJarClasses has to be static to begin with, especially if its creation is tied to creating a new Cache to start with. Can you provide some intuition for this?

2017-11-24 22:08 UTC, august782 commented on starts-core/src/main/java/edu/illinois/starts/helpers/Loadables.java
> +            transitiveClosure = getTransitiveClosurePerClass(graph, affectedTests);
These calls to getTransitiveClosurePerClass are replacing the one that uses classesToAnalyze as an argument. However, so far, it feels as if classesToAnalyze are decomposed into changedClasses and newClasses. Where does affectedTests/allTests fit in? Would there be any problems with calling on just the tests and not all classes as was being done before?

2017-11-24 22:22 UTC, august782 commented on starts-core/src/main/java/edu/illinois/starts/helpers/Loadables.java
> +                allTransitiveClosure = getTransitiveClosurePerClass(graph, allTests);
So no matter what, it is necessary to get the transitive closure based on all tests? Is there any way to do this safely incrementally to get the correct unreached part (I don't think this is very critical though, as transitive closure computation should be fairly fast...)?

2017-11-24 22:26 UTC, august782 commented on starts-core/src/main/java/edu/illinois/starts/helpers/Loadables.java
> +            args.addAll(changedClasses);
If for an incrementalUpdate there is no need to use localPaths, can that logic be propagated earlier to make sure localPaths doesn't even need to be computed?

2017-11-24 22:30 UTC, august782 commented on starts-core/src/main/java/edu/illinois/starts/helpers/RTSUtil.java
> +
Remove this empty line.

2017-11-24 22:36 UTC, august782 commented on starts-core/src/main/java/edu/illinois/starts/helpers/RTSUtil.java
> +                deps.put(left, new HashSet<>(Collections.singletonList(right)));
What's the reasoning for use of the singletonList?

2017-11-24 22:43 UTC, august782 commented on starts-core/src/main/java/edu/illinois/starts/helpers/ZLCHelper.java
> +                                     Set<String> changed, Set<String> newClasses, boolean incrementalUpdate) {
To keep things consistent, shouldn't changed actually be changedClasses?

2017-11-24 22:47 UTC, august782 commented on starts-core/src/main/java/edu/illinois/starts/helpers/ZLCHelper.java
> +                        if (tests.isEmpty()) {
If tests is empty, is it correct to set the mapping to be empty (that no tests cover this class), or to leave the old dependencies from before? If the former, then this check for isEmpty and then continuing should not be here.

2017-11-24 22:49 UTC, august782 commented on starts-core/src/main/java/edu/illinois/starts/helpers/ZLCHelper.java
> +        LOGGER.log(Level.FINE, "[TIME]UPDATING CHECKSUMS: " + Writer.millsToSeconds(end - start));
Why is it important to change the logging message? In particular, it might be important to keep the same stuff in the [].

2017-11-24 22:52 UTC, august782 commented on starts-core/src/main/java/edu/illinois/starts/helpers/ZLCHelper.java
> +        // for each dep, find it's url, checksum and tests that depend on it
it's -> its

2017-11-24 22:53 UTC, august782 commented on starts-core/src/main/java/edu/illinois/starts/helpers/ZLCHelper.java
> +        handleNewData(testDeps, loader, deps, zlcData);
So technically handleNewData() doesn't just handle the new data, it can be used to handle any data (as shown here)? Should the name be changed to reflect this, so it can just be handleData()?

2017-11-24 22:57 UTC, august782 commented on starts-plugin/src/main/java/edu/illinois/starts/jdeps/BaseMojo.java
> +        Loadables loadables = new Loadables(changedClasses, newClasses,
Did classesToAnalyze from before contain test classes as well? Is it safe to not include tests as part of the arguments?

2017-11-24 22:58 UTC, august782 commented on starts-plugin/src/main/java/edu/illinois/starts/jdeps/BaseMojo.java
> +        allTests.addAll(nonAffected);
nonAffected is just non-affected classes, right? It does not include non-test classes?

2017-11-24 23:00 UTC, august782 commented on starts-plugin/src/main/java/edu/illinois/starts/jdeps/BaseMojo.java
> +        loadables.setAffectedTests(new ArrayList<>(affectedTests));
Why are affectedTests and allTests being set explicitly through methods to loadables? Why should they not be set in the constructor, as with changedClasses/newClasses?

2017-11-24 23:10 UTC, august782 commented on starts-plugin/src/main/java/edu/illinois/starts/jdeps/DiffMojo.java
> +            Result result = prepareForNextRun(sfPathString, sfClassPath, new ArrayList<>(changedClasses),
Why is it important to construct new objects for changedClasses and newClasses but not for affectedTests or nonAffected?

2017-11-24 23:12 UTC, august782 commented on starts-plugin/src/main/java/edu/illinois/starts/jdeps/DiffMojo.java
> +                //ZLCHelper zlcHelper = new ZLCHelper();
So before, this was being called and was then clearing out that static map. Was that a bug then?

2017-11-24 23:14 UTC, august782 commented on starts-plugin/src/main/java/edu/illinois/starts/jdeps/SelectMojo.java
> +        Set<String> changedClasses  = data == null ? new HashSet<String>() : data.getValue();
There's an extra space before " =  data"

2017-11-29 19:20 UTC, denizarsan requested changes
Functionally it looks fine to me.

I honestly don't know if we can configure Checkstyle to check for space after `//` but just for the sake of consistency, I tried to mark the places where you were missing one.

2017-11-29 19:20 UTC, denizarsan commented on starts-core/src/main/java/edu/illinois/starts/helpers/Loadables.java
> +            //TODO: findUnreached may be affected by incrementally finding test dependencies
Space after `//`

2017-11-29 19:20 UTC, denizarsan commented on starts-core/src/main/java/edu/illinois/starts/helpers/ZLCHelper.java
> +//    }
I think you should remove this code rather than commenting it out.

2017-11-29 19:20 UTC, denizarsan commented on starts-core/src/main/java/edu/illinois/starts/helpers/ZLCHelper.java
> +                    changedClasses.add(stringURL);//contain changed/deleted classes and jars
Add space after `//` in `//contain..` (I don't know if this can be checked by Checkstyle)

2017-11-29 19:20 UTC, denizarsan commented on starts-plugin/src/main/java/edu/illinois/starts/jdeps/BaseMojo.java
> +                //get All dependencies that this project has, including the project itself
Space after `//`

2017-11-29 19:20 UTC, denizarsan commented on starts-plugin/src/main/java/edu/illinois/starts/jdeps/DiffMojo.java
> +    //TODO: set this boolean to true only for static reflectionAnalyses with * (border, string, naive)?
Space after `//`

2017-11-29 19:20 UTC, denizarsan commented on starts-plugin/src/main/java/edu/illinois/starts/jdeps/DiffMojo.java
> +            ZLCHelper zlcHelper = new ZLCHelper();// be careful about this. this clears the static zlcDataMap
Can you add a more specific comment for this? What should one do or not do? What does "being careful" entail?

2017-11-29 19:20 UTC, denizarsan commented on starts-plugin/src/main/java/edu/illinois/starts/jdeps/DiffMojo.java
> +                //ZLCHelper zlcHelper = new ZLCHelper();
Remove this commented line too.

2017-11-29 19:20 UTC, denizarsan commented on starts-plugin/src/main/java/edu/illinois/starts/jdeps/ImpactedMojo.java
> +        //ZLCHelper zlcHelper = new ZLCHelper();// call this would clear zlcDataMap
Just remove the commented line.

2017-11-29 19:20 UTC, denizarsan commented on starts-plugin/src/main/java/edu/illinois/starts/jdeps/RunMojo.java
> +        setIncludesExcludes();//set non affected tests in surefire
Space after `//`. Alternatively, you can merge these two inline comments into a one block level comment.

2017-11-29 19:20 UTC, denizarsan commented on starts-plugin/src/main/java/edu/illinois/starts/jdeps/RunMojo.java
> +        setChangedAndNonaffected();//get changed/deleted classes (in project and in jar)
Space after `//`

2017-11-29 19:20 UTC, denizarsan commented on starts-plugin/src/main/java/edu/illinois/starts/jdeps/RunMojo.java
> +            //update dependency graph and zlc mapping for run usage in next revision
Space after `//`

2017-11-29 19:20 UTC, denizarsan commented on starts-core/src/main/java/edu/illinois/starts/helpers/ZLCHelper.java
> +//    }
Can you just remove the commented out code?

2017-12-21 07:10 UTC, hksskh commented on starts-core/src/main/java/edu/illinois/starts/helpers/Cache.java
> +        newJarClasses = new HashSet<>();// only place to clear new jar classes. carefully call this
already remove this newJarClasses. Since we will run all tests when there are changes in classpath or jar checksums, we actually do not need to track new jar classes in this way.

2017-12-21 07:23 UTC, hksskh commented on starts-core/src/main/java/edu/illinois/starts/helpers/Loadables.java
> +            transitiveClosure = getTransitiveClosurePerClass(graph, affectedTests);
The classesToAnalyze passed to Lodables in current STARTS is from prepareForNextRun() in BaseMojo. And the classesToAnalyze passed to this function in BaseMojo is the allTests when calling from DiffMojo and the allClasses when calling from DiffMojo. 
For transitive closure, we only need to find transitive closure for allTests (for DiffMojo) or for allClasses (for impactedmojo), right?
In my modifications, when prepareForNextRun() in BaseMojo is called from DiffMojo, affectedTests and nonaffected tests are passed in, so allTests == classesToAnalyze.
when prepareForNextRun() is called from ImpactedMojo, I passed allClasses as affected and empty list as nonaffected, so the allTests in this case is actually allClasses, so allTests == classesToAnalyze.
Therefore, I think my changes would not cause the problem in your question. However, it truly seems confusing as allTests in this change can be allTests in one case and be allClasses in another case. How do you think I can make this clearer?
Does this long comment makes sense to you? :)

2017-12-21 07:28 UTC, hksskh commented on starts-core/src/main/java/edu/illinois/starts/helpers/Loadables.java
> +                allTransitiveClosure = getTransitiveClosurePerClass(graph, allTests);
well I did not take incrementally finding unreached into consideration before! So in order to do this, we need to always make complete transitive closure for allTests, in an incremental way. Then we may need to store transitive closure in some files. However, since find unreached has also been made an option in my changes, I think it is safer to keep find unreached right in this way. Anyway, I may try to look into it after fixing this pull request. :)

2017-12-21 07:33 UTC, hksskh commented on starts-core/src/main/java/edu/illinois/starts/helpers/Loadables.java
> +            args.addAll(changedClasses);
since jdepsClassPath is computed from this localPaths, so I think we may still need to compute this localPaths even in incremental cases.

for the format, in current STARTS the localPaths are actually directory paths to compiled classes and target classes. For the changedClasses and newClasses that I passed in, they are fully qualified names. I have tried on commons-math and jdeps can works with both cases, so I think this should be fine.

2017-12-21 07:34 UTC, hksskh commented on starts-core/src/main/java/edu/illinois/starts/helpers/RTSUtil.java
> +
done.

2017-12-21 07:35 UTC, hksskh commented on starts-core/src/main/java/edu/illinois/starts/helpers/RTSUtil.java
> +                deps.put(left, new HashSet<>(Collections.singletonList(right)));
this is suggested by my Intellij, so I simply refactor it automatically.

2017-12-21 07:36 UTC, hksskh commented on starts-core/src/main/java/edu/illinois/starts/helpers/ZLCHelper.java
> +                                     Set<String> changed, Set<String> newClasses, boolean incrementalUpdate) {
fixed.

2017-12-21 07:39 UTC, hksskh commented on starts-core/src/main/java/edu/illinois/starts/helpers/ZLCHelper.java
> +                        if (tests.isEmpty()) {
fixed. update tests when it's not empty, and leave it as before when empty.

2017-12-21 07:42 UTC, hksskh commented on starts-core/src/main/java/edu/illinois/starts/helpers/ZLCHelper.java
> +        LOGGER.log(Level.FINE, "[TIME]UPDATING CHECKSUMS: " + Writer.millsToSeconds(end - start));
fixed.

2017-12-21 07:43 UTC, hksskh commented on starts-core/src/main/java/edu/illinois/starts/helpers/ZLCHelper.java
> +        // for each dep, find it's url, checksum and tests that depend on it
fixed.

2017-12-21 07:46 UTC, hksskh commented on starts-core/src/main/java/edu/illinois/starts/helpers/ZLCHelper.java
> +        handleNewData(testDeps, loader, deps, zlcData);
fixed. changed function name to addZLCData.

2017-12-21 07:48 UTC, hksskh commented on starts-plugin/src/main/java/edu/illinois/starts/jdeps/BaseMojo.java
> +                //get All dependencies that this project has, including the project itself
fixed.

2017-12-21 07:52 UTC, hksskh commented on starts-plugin/src/main/java/edu/illinois/starts/jdeps/BaseMojo.java
> +        Loadables loadables = new Loadables(changedClasses, newClasses,
For the classesToAnalyze before, it is actually allTests if called from DiffMojo, and is allClasses if called from ImpactedMojo. 
Correspondingly, in my changes, the changedClasses and newClasses also include changed classes, if called from DiffMojo.

2017-12-21 07:55 UTC, hksskh commented on starts-plugin/src/main/java/edu/illinois/starts/jdeps/BaseMojo.java
> +        allTests.addAll(nonAffected);
sorry for these confusions in names. for nonAffected, it is nonaffected tests when called from DiffMojo, and it is nonaffected classes if called from ImpactedMojo. Since this prepareForNextRun() function in BaseMojo is called both from DiffMojo and ImpactedMojo, these parameters can mean differently, so the name seems confusing. How do you think I can  fix this name confusion?

2017-12-21 08:04 UTC, hksskh commented on starts-plugin/src/main/java/edu/illinois/starts/jdeps/BaseMojo.java
> +        loadables.setAffectedTests(new ArrayList<>(affectedTests));
fixed.

2017-12-21 08:08 UTC, hksskh commented on starts-plugin/src/main/java/edu/illinois/starts/jdeps/DiffMojo.java
> +            Result result = prepareForNextRun(sfPathString, sfClassPath, new ArrayList<>(changedClasses),
since the parameter type in prepareForNextRun function are Lists for changedClasses and newClasses, but they are actually Sets in DiffMojo, I need to reconstruct Lists from them to match parameter type (this parameter type was set in current STARTS). This seems not efficient, do you think I should change the parameter types in prepareForNextRun function?

2017-12-21 08:10 UTC, hksskh commented on starts-plugin/src/main/java/edu/illinois/starts/jdeps/DiffMojo.java
> +                //ZLCHelper zlcHelper = new ZLCHelper();
yeah this is not a bug before since we do not actually use this static map before, However it causes problems in my changes since I need this static map to incrementally update ZLC file, so I simply remove this line here.

2017-12-21 08:12 UTC, hksskh commented on starts-plugin/src/main/java/edu/illinois/starts/jdeps/SelectMojo.java
> +        Set<String> changedClasses  = data == null ? new HashSet<String>() : data.getValue();
fixed.

2017-12-21 08:12 UTC, hksskh commented on starts-core/src/main/java/edu/illinois/starts/helpers/Loadables.java
> +            //TODO: findUnreached may be affected by incrementally finding test dependencies
fixed.

2017-12-21 08:13 UTC, hksskh commented on starts-core/src/main/java/edu/illinois/starts/helpers/ZLCHelper.java
> +//    }
fixed.

2017-12-21 08:14 UTC, hksskh commented on starts-core/src/main/java/edu/illinois/starts/helpers/ZLCHelper.java
> +//    }
fixed.

2017-12-21 08:15 UTC, hksskh commented on starts-core/src/main/java/edu/illinois/starts/helpers/ZLCHelper.java
> +                    changedClasses.add(stringURL);//contain changed/deleted classes and jars
fixed.

2017-12-21 08:16 UTC, hksskh commented on starts-plugin/src/main/java/edu/illinois/starts/jdeps/DiffMojo.java
> +    //TODO: set this boolean to true only for static reflectionAnalyses with * (border, string, naive)?
fixed.

2017-12-21 08:17 UTC, hksskh commented on starts-plugin/src/main/java/edu/illinois/starts/jdeps/DiffMojo.java
> +            ZLCHelper zlcHelper = new ZLCHelper();// be careful about this. this clears the static zlcDataMap
fixed.

2017-12-21 08:20 UTC, hksskh commented on starts-plugin/src/main/java/edu/illinois/starts/jdeps/ImpactedMojo.java
> +        //ZLCHelper zlcHelper = new ZLCHelper();// call this would clear zlcDataMap
fixed.

2017-12-21 08:21 UTC, hksskh commented on starts-plugin/src/main/java/edu/illinois/starts/jdeps/RunMojo.java
> +        setChangedAndNonaffected();//get changed/deleted classes (in project and in jar)
fixed.

2017-12-21 08:22 UTC, hksskh commented on starts-plugin/src/main/java/edu/illinois/starts/jdeps/RunMojo.java
> +        setIncludesExcludes();//set non affected tests in surefire
fixed.

2017-12-21 08:23 UTC, hksskh commented on starts-plugin/src/main/java/edu/illinois/starts/jdeps/RunMojo.java
> +            //update dependency graph and zlc mapping for run usage in next revision
fixed.

2017-12-21 09:23 UTC, hksskh commented
@august782 @denizarsan I have add replies to all your comments. Please check them and see if any other changes are needed.

2023-08-22 18:23 UTC, owolabileg commented
closing this PR as the requested changes were not addressed since 2017.

2023-08-22 18:23 UTC, closed without merging