Optimize ZLC file format
TestingResearchIllinois/starts pull request #80
Opened 2021-05-26 18:51 UTC by jtx1999

A parameter `zlcFormat` is added, which controls how the deps.zlc is stored. It can be set to `PLAIN_TEXT` or `INDEXED`.
If set to `PLAIN_TEXT`, deps.zlc behaviors the same as before.
If set to `INDEXED`, indices of tests are stored in deps.zlc, instead of the full URLs.

An integration test is added for `zlcFormat=INDEXED`. The test is copied from `multilevel-no-parents-or-siblings-it`.

2021-05-26 18:57 UTC, jtx1999 commented
@owolabileg Please review

2021-05-26 19:23 UTC, owolabileg requested changes

2021-05-26 19:23 UTC, owolabileg commented on starts-core/src/main/java/edu/illinois/starts/data/ZLCData.java
> +    private Set<Pair<String, Integer>> tests;
shouldn't this change depending on the zlcformat?

2021-05-26 19:23 UTC, owolabileg commented on starts-core/src/main/java/edu/illinois/starts/data/ZLCData.java
> +            case INDEXED:
Add comments to explain what INDEXED and PLAIN_TEXT mean

2021-05-26 19:23 UTC, owolabileg commented on starts-core/src/main/java/edu/illinois/starts/data/ZLCFile.java
> +public class ZLCFile {
Why call this a "File"?

2021-05-26 19:23 UTC, owolabileg commented on starts-core/src/main/java/edu/illinois/starts/helpers/Writer.java
>      public static void writeMapToFile(Map map, String filename) {
Do we still need this write method? Why?

2021-05-26 21:48 UTC, jtx1999 commented on starts-core/src/main/java/edu/illinois/starts/data/ZLCFile.java
> +public class ZLCFile {
Because this class represents the content of the deps.zlc file

2021-05-26 21:50 UTC, jtx1999 commented on starts-core/src/main/java/edu/illinois/starts/helpers/Writer.java
>      public static void writeMapToFile(Map map, String filename) {
Are you referring to the method `writeMapToFile(Map map, String filename)`? That's still used in `Loadables.java` to write log files.

2021-05-26 21:52 UTC, jtx1999 commented on starts-core/src/main/java/edu/illinois/starts/data/ZLCData.java
> +            case INDEXED:
Added in `ZLCFormat.java`.

2021-05-26 21:52 UTC, jtx1999 commented on starts-core/src/main/java/edu/illinois/starts/data/ZLCData.java
> +    private Set<Pair<String, Integer>> tests;
Updated

2021-05-27 21:52 UTC, jtx1999 commented
@owolabileg Please review

2021-05-27 22:19 UTC, owolabileg commented on starts-core/src/main/java/edu/illinois/starts/data/ZLCFile.java
> +public class ZLCFile {
Why not then call it something like ZLCFileData or ZLCFileContent?

2021-05-27 22:21 UTC, owolabileg commented on starts-core/src/main/java/edu/illinois/starts/data/ZLCData.java
> -    }
why is this deleted?

2021-05-27 22:24 UTC, jtx1999 commented on starts-core/src/main/java/edu/illinois/starts/data/ZLCFile.java
> +public class ZLCFile {
Refactored to ZLCFileContent

2021-05-27 22:25 UTC, jtx1999 commented on starts-core/src/main/java/edu/illinois/starts/data/ZLCData.java
> -    }
This is not used anywhere

2021-05-27 22:29 UTC, owolabileg commented on starts-core/src/main/java/edu/illinois/starts/data/ZLCData.java
> -    }
In general, it is better to open new PRs instead of mixing unrelated changes in the same PR.

2021-05-27 22:40 UTC, owolabileg commented
@jtx1999 do you need to update the pom.xml?:

![image](https://user-images.githubusercontent.com/4887692/119905882-0ee76500-bf1b-11eb-8c62-fcf4414031b6.png)

2021-05-27 22:42 UTC, owolabileg commented
@jtx1999 do you need to update the pom.xml?:

![image](https://user-images.githubusercontent.com/4887692/119906000-5110a680-bf1b-11eb-9ac6-832755f90272.png)

2021-05-27 22:54 UTC, jtx1999 commented
> @jtx1999 do you need to update the pom.xml?:
> 
> ![image](https://user-images.githubusercontent.com/4887692/119906000-5110a680-bf1b-11eb-9ac6-832755f90272.png)

@owolabileg Rebasing on master

2021-05-28 17:03 UTC, jtx1999 commented
@owolabileg Please review

2021-05-28 19:38 UTC, merged