Refactored LibraryOptions to TransitiveClosureOptions
TestingResearchIllinois/starts pull request #96
Opened 2022-10-07 18:12 UTC by marques-valeria

Also added a setter to ImpactedMojo for use in eMOP.

2022-10-11 00:44 UTC, bcarlet commented
Looks good.

2022-10-11 02:27 UTC, ayakayorihiro approved these changes
Looks great to me!

2022-10-11 02:34 UTC, owolabileg requested changes

2022-10-11 02:34 UTC, owolabileg commented on starts-core/src/main/java/edu/illinois/starts/enums/TransitiveClosureOptions.java
> +    TRANS,
TRANS --> TRANSITIVE

2022-10-11 02:34 UTC, owolabileg commented on starts-core/src/main/java/edu/illinois/starts/enums/TransitiveClosureOptions.java
> +    TRANS_AND_INVERSE_TRANS,
TRANS --> TRANSITIVE

2022-10-11 02:34 UTC, owolabileg commented on starts-core/src/main/java/edu/illinois/starts/enums/TransitiveClosureOptions.java
> +    TRANS_OF_INVERSE_TRANS,
TRANS --> TRANSITIVE

2022-10-11 02:34 UTC, owolabileg commented on starts-core/src/main/java/edu/illinois/starts/helpers/Loadables.java
> +            Set<String> closure = new HashSet<>();
closure --> transitiveClosure (change everywhere)

2022-10-11 02:34 UTC, owolabileg commented on starts-core/src/main/java/edu/illinois/starts/helpers/Loadables.java
> +                case TRANS:
TRANS --> TRANSITIVE

2022-10-11 02:34 UTC, owolabileg commented on starts-core/src/main/java/edu/illinois/starts/helpers/Loadables.java
> +                case TRANS_AND_INVERSE_TRANS:
TRANS --> TRANSITIVE

2022-10-11 02:34 UTC, owolabileg commented on starts-core/src/main/java/edu/illinois/starts/helpers/Loadables.java
> +                case TRANS_OF_INVERSE_TRANS:
TRANS --> TRANSITIVE

2022-10-11 02:34 UTC, owolabileg commented on starts-plugin/src/main/java/edu/illinois/starts/jdeps/DiffMojo.java
> +                    computeUnreached, TransitiveClosureOptions.TRANS);
TRANS --> TRANSITIVE

2022-10-11 02:34 UTC, owolabileg commented on starts-plugin/src/main/java/edu/illinois/starts/jdeps/ImpactedMojo.java
> +    @Parameter(property = "closureOption", defaultValue = "TRANS")
TRANS --> TRANSITIVE

2022-10-11 02:35 UTC, owolabileg commented
@marques-valeria please make these minor changes and then I will merge.

2022-10-11 10:52 UTC, owolabileg commented on starts-core/src/main/java/edu/illinois/starts/enums/TransitiveClosureOptions.java
> + * Options for computing transitive closure.
Can you please add some an example here, so that it is clearer in the future what these options are?

You can just put the edges of the graph like so:

A --> B
B --> C

Then say what each option would compute from the graph.

Please use the example from the 2019 paper, say what these options map to in that paper, and put a link to the paper here.

2022-10-12 11:09 UTC, owolabileg commented on starts-core/src/main/java/edu/illinois/starts/enums/TransitiveClosureOptions.java
> + * These options correspond to ps3, ps2, and ps1, respectively, in the aforementioned paper
On your next PR, please add a "period" at the end of this sentence.

2022-10-12 11:10 UTC, merged